[project]
name = "analytics-utils"
version = "0.1.4"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pandas>=2.2.3",
    "pandera>=0.23.1",
    "psycopg2-binary>=2.9.10",
]
